### ISSUE TITLE
'Calculator' object has no attribute 'window'

### ISSUE THREAD

**Issue by talhayaseen57** [programiz/Calculator#4]
I am using python3 --version 3.10.6 and tkinter --version 3.8.
I executed a few lines of code:
```
import tkinter as tk


class Calculator:
    def __int__(self):
        self.window = tk.Tk()
        self.window.geometry("363x497")
        self.window.resizable(0, 0)
        self.window.title("Calculator App")

    def run(self):
        self.window.mainloop()


if __name__ == "__main__":
    calc = Calculator()
    calc.run()
```

But I got this error:
```
Traceback (most recent call last):
  File "/home/bhatti/Documents/Programming/Tkinter GUI Calculator/calculator.py", line 17, in <module>
    calc.run()
  File "/home/bhatti/Documents/Programming/Tkinter GUI Calculator/calculator.py", line 12, in run
    self.window.mainloop()
AttributeError: 'Calculator' object has no attribute 'window'

Process finished with exit code 1
```

**Comment by dishant440** [comment]
ty

> I am using python3 --version 3.10.6 and tkinter --version 3.8. I executed a few lines of code:
> 
> ```
> import tkinter as tk
> 
> 
> class Calculator:
>     def __int__(self):
>         self.window = tk.Tk()
>         self.window.geometry("363x497")
>         self.window.resizable(0, 0)
>         self.window.title("Calculator App")
> 
>     def run(self):
>         self.window.mainloop()
> 
> 
> if __name__ == "__main__":
>     calc = Calculator()
>     calc.run()
> ```
> 
> But I got this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/bhatti/Documents/Programming/Tkinter GUI Calculator/calculator.py", line 17, in <module>
>     calc.run()
>   File "/home/bhatti/Documents/Programming/Tkinter GUI Calculator/calculator.py", line 12, in run
>     self.window.mainloop()
> AttributeError: 'Calculator' object has no attribute 'window'
> 
> Process finished with exit code 1
> ```
there is typing error when defining init function there is ` i  ` missing
